`version: '3'
services:
  linkstack:
    container_name: linkstack
    image: linkstackorg/linkstack
    environment:
      - HTTP_SERVER_NAME="domain.me" 
      - HTTPS_SERVER_NAME="domain.me"
      - SERVER_ADMIN="admin@example.xyz"
      - TZ="Europe/Berlin"
      - PHP_MEMORY_LIMIT="512M"
      - UPLOAD_MAX_FILESIZE="8M"
    restart: always
    volumes:
      - /opt/containers/ls_data/httpdocs:/htdocs
      - /opt/containers/ls_data/ssl_apache:/etc/ssl/apache2
    ports:
      - '8080:80'
      - '4437:443'
    networks:
      - traefik_web
networks:
  traefik_web:
   external: true`
